# Generated by Django 5.0.7 on 2024-08-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
